/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Cars;
import model.CarsList;

/**
 *
 * @author Administrator
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private CarsList carsList;
    
    public CreateJPanel(CarsList carsList) {
        initComponents();
        this.carsList = carsList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        blbBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        chbAvail = new javax.swing.JCheckBox();
        lblAvail = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create a Car");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 761, -1));

        blbBrand.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        blbBrand.setText("Brand:");
        add(blbBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 89, -1, -1));
        add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 88, 101, -1));

        lblYear.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblYear.setText("Year of Manufacture:");
        add(lblYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 128, -1, -1));
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 127, 101, -1));

        lblSeats.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblSeats.setText("Seat:");
        add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 167, -1, -1));
        add(txtSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 166, 101, -1));

        lblId.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblId.setText("Serial Number:");
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 206, -1, -1));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 205, 101, -1));

        lblName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblName.setText("Model Numder:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 245, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 244, 101, -1));

        chbAvail.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        chbAvail.setText("Available");
        add(chbAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 322, -1, -1));

        lblAvail.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblAvail.setText("Availability:");
        add(lblAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 326, -1, -1));

        btnSave.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 365, -1, -1));

        lblCity.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 284, 89, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 283, 101, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        if(txtBrand.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input Brand!","Warning", JOptionPane.ERROR_MESSAGE);
            txtBrand.setText("");
            return;
        }
        
        if(!txtYear.getText().matches("^20([0-1][0-9]|2[0-1])$")){   
            JOptionPane.showMessageDialog(this, "Please input Year of Manufacture!","Warning", JOptionPane.ERROR_MESSAGE);
            txtYear.setText("");
            return;
        }
        
        if(txtSeats.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input number of Seats!","Warning", JOptionPane.ERROR_MESSAGE);
            txtSeats.setText("");
            return;
        }else{
            if(Integer.parseInt(txtSeats.getText()) >= 10 || Integer.parseInt(txtSeats.getText()) <= 0){
                JOptionPane.showMessageDialog(this, "Please input number of Seats!","Warning", JOptionPane.ERROR_MESSAGE);
                txtSeats.setText("");
                return;
            }
        }
        
        if(txtId.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input Serial Number!","Warning", JOptionPane.ERROR_MESSAGE);
            txtId.setText("");
            return;
        }
        
        for(Cars car : carsList.getCarsList()){
            System.out.println(car.getId());
            if(car.getId() == Integer.parseInt(txtId.getText())){
                    JOptionPane.showMessageDialog(this, "Please input Serial Number!","Warning", JOptionPane.ERROR_MESSAGE);
                    txtId.setText("");
                    return;
                }
            }
        
        if(txtName.getText().isEmpty()){   
            JOptionPane.showMessageDialog(this, "Please input Model Numder!","Warning", JOptionPane.ERROR_MESSAGE);
            txtName.setText("");
            return;
        }
        
        if(!txtCity.getText().matches("[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*")){   
            JOptionPane.showMessageDialog(this, "Please input City!","Warning", JOptionPane.ERROR_MESSAGE);
            txtCity.setText("");
            return;
        }
        Cars car = carsList.addCars();
        boolean avail = chbAvail.isSelected();
        car.setAvail(avail);
        car.setBrand(txtBrand.getText());
        car.setYear(txtYear.getText());
        car.setSeats(Integer.parseInt(txtSeats.getText())); 
        car.setId(Integer.parseInt(txtId.getText()));
        car.setName(txtName.getText());
        car.setCity(txtCity.getText());
        
        JOptionPane.showMessageDialog(this, "New Cars Added.");
        
        txtBrand.setText("");
        txtYear.setText("");
        txtSeats.setText("");
        txtId.setText("");
        txtName.setText("");
        txtCity.setText("");
        chbAvail.setSelected(false);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbBrand;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chbAvail;
    private javax.swing.JLabel lblAvail;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
