/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Cars;
import model.CarsList;

/**
 *
 * @author Administrator
 */
public class SchIdJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchIdJPanel
     */
    private CarsList carsList;
    
    public SchIdJPanel(CarsList carsList) {
        initComponents();
        this.carsList = carsList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewName = new javax.swing.JLabel();
        lblViewBrand = new javax.swing.JLabel();
        txtViewBrand = new javax.swing.JTextField();
        lblViewYear = new javax.swing.JLabel();
        lblViewCity = new javax.swing.JLabel();
        txtViewYear = new javax.swing.JTextField();
        lblViewSeats = new javax.swing.JLabel();
        txtViewSeats = new javax.swing.JTextField();
        lblViewAvail = new javax.swing.JLabel();
        txtViewAvail = new javax.swing.JTextField();
        lblViewId = new javax.swing.JLabel();
        txtViewId = new javax.swing.JTextField();
        btnId = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtViewName = new javax.swing.JTextField();
        txtViewCity = new javax.swing.JTextField();

        lblViewName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewName.setText("Model Numder:");

        lblViewBrand.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewBrand.setText("Brand:");

        lblViewYear.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewYear.setText("Year of Manufacture:");

        lblViewCity.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblViewCity.setText("City:");

        lblViewSeats.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewSeats.setText("Seat:");

        lblViewAvail.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewAvail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblViewAvail.setText("Availability:");

        lblViewId.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        lblViewId.setText("Serial Number:");

        btnId.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        btnId.setText("Search");
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Search Car with Serial Number");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel1.setText("Input the Id of the car you want to update:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblViewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewName)
                    .addComponent(lblViewId)
                    .addComponent(lblViewSeats)
                    .addComponent(lblViewAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewYear)
                    .addComponent(lblViewBrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(356, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtViewId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtViewYear, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtViewBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnId))
                            .addComponent(txtViewSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtViewAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtViewCity, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtViewAvail, txtViewBrand, txtViewCity, txtViewId, txtViewName, txtViewSeats, txtViewYear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTitle)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewBrand))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewYear)
                    .addComponent(txtViewYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewSeats)
                    .addComponent(txtViewSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewId)
                    .addComponent(txtViewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewName)
                    .addComponent(txtViewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewCity)
                    .addComponent(txtViewCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAvail)
                    .addComponent(txtViewAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnId, jLabel1, txtId});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtViewAvail, txtViewBrand, txtViewCity, txtViewId, txtViewName, txtViewSeats, txtViewYear});

    }// </editor-fold>//GEN-END:initComponents

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
        // TODO add your handling code here:
        boolean find = false;
        for(Cars car : carsList.getCarsList()){
            if(car.getId() == Integer.parseInt(txtId.getText())){
                txtViewBrand.setText(car.getBrand());
                txtViewYear.setText(car.getYear());
                txtViewSeats.setText(String.valueOf(car.getSeats()));
                txtViewId.setText(String.valueOf(car.getId()));
                txtViewName.setText(car.getName());
                txtViewCity.setText(car.getCity());
                if(car.isAvail()){
                    txtViewAvail.setText("Yes");
                }else{
                    txtViewAvail.setText("No");
                }
                find = true;
            }
        }
        if(!find){
            JOptionPane.showMessageDialog(this, "No car is Found!"); 
            txtViewName.setText("");
            txtViewAvail.setText("");
            txtViewBrand.setText("");
            txtViewCity.setText("");
            txtViewId.setText("");
            txtViewSeats.setText("");
            txtViewYear.setText("");
        }
        txtId.setText("");
    }//GEN-LAST:event_btnIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblViewAvail;
    private javax.swing.JLabel lblViewBrand;
    private javax.swing.JLabel lblViewCity;
    private javax.swing.JLabel lblViewId;
    private javax.swing.JLabel lblViewName;
    private javax.swing.JLabel lblViewSeats;
    private javax.swing.JLabel lblViewYear;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtViewAvail;
    private javax.swing.JTextField txtViewBrand;
    private javax.swing.JTextField txtViewCity;
    private javax.swing.JTextField txtViewId;
    private javax.swing.JTextField txtViewName;
    private javax.swing.JTextField txtViewSeats;
    private javax.swing.JTextField txtViewYear;
    // End of variables declaration//GEN-END:variables
}
